build-idgen:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN --mount=type=cache,target=/go/pkg \
        go install github.com/mritd/idgen@latest

    SAVE ARTIFACT /go/bin/idgen

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    BUILD +build-idgen
    
    COPY +build-idgen/idgen /usr/bin/idgen
    
    ENTRYPOINT ["idgen"]
    CMD ["server"]

    SAVE IMAGE --push mritd/idgen:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +build
