VERSION 0.7

FROM mritd/alpine

ARG DATE_TAG=$(date "+%Y%m%d%H%M%S")

build:
    DO ../udcs/image+NODE
    DO ../udcs+LABEL
    DO ../udcs/os/debian+UPGRADE
    DO ../udcs/os/debian+COMMON_PKG
    DO ../udcs/os/debian+LOCALE
    DO ../udcs/os/debian+TIMEZONE
    DO ../udcs/os/debian+INSTALL_BUILD_BASE
    DO ../udcs+TINI

    ENV NPM_CACHE_DIR /data/npm_cache
    ENV NPM_DIST https://npm.taobao.org/dist
    ENV NPM_REGISTRY https://registry.npm.taobao.org

    RUN apt update \
        && apt install python2 -y \
        && npm install -g npm \
        && npm install -g pnpm fis3

    COPY cnpm /usr/local/bin/cnpm
    
    ENTRYPOINT ["tini","--"]

    CMD ["node"]

    SAVE IMAGE --push mritd/nodebuild:${DATE_TAG} mritd/nodebuild:latest

all:
    BUILD --platform=linux/amd64 +build
