VERSION 0.8

build:
    DO ../.udcs/image+NODE
    DO ../.udcs+LABEL
    DO ../.udcs/os/debian+UPGRADE
    DO ../.udcs/os/debian+COMMON_PKG
    DO ../.udcs/os/debian+LOCALE
    DO ../.udcs/os/debian+TIMEZONE
    DO ../.udcs/os/debian+INSTALL_BUILD_BASE
    DO ../.udcs+TINI

    ARG --required BUILD_DATE

    ENV NPM_CACHE_DIR /data/npm_cache
    ENV NPM_DIST https://npmmirror.com/mirrors/node
    ENV NPM_REGISTRY https://registry.npmmirror.com

    RUN apt update -qq \
        && apt install -qq python2 -y \
        && npm install -g npm \
        && npm install -g pnpm fis3

    COPY cnpm /usr/local/bin/cnpm
    
    ENTRYPOINT ["tini","--"]

    CMD ["node"]

    SAVE IMAGE --push mritd/nodebuild:${BUILD_DATE} mritd/nodebuild:latest

all:
    # DO ../.udcs+BUILD_DATE
    FROM mritd/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")

    BUILD --platform=linux/amd64 +build --BUILD_DATE=${BUILD_DATE}
