VERSION 0.7

build:
    DO ../udcs/image+NODE
    DO ../udcs+LABEL
    DO ../udcs/os/debian+UPGRADE
    DO ../udcs/os/debian+COMMON_PKG
    DO ../udcs/os/debian+LOCALE
    DO ../udcs/os/debian+TIMEZONE
    DO ../udcs/os/debian+INSTALL_BUILD_BASE
    DO ../udcs+TINI

    ARG --required BUILD_DATE

    ENV NPM_CACHE_DIR /data/npm_cache
    ENV NPM_DIST https://npm.taobao.org/dist
    ENV NPM_REGISTRY https://registry.npm.taobao.org

    RUN apt update \
        && apt install python2 -y \
        && npm install -g npm \
        && npm install -g pnpm fis3

    COPY cnpm /usr/local/bin/cnpm
    
    ENTRYPOINT ["tini","--"]

    CMD ["node"]

    SAVE IMAGE --push ghcr.io/mritd/nodebuild:${BUILD_DATE} ghcr.io/mritd/nodebuild:latest

all:
    # DO ../udcs+BUILD_DATE
    FROM mritd/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")

    BUILD --platform=linux/amd64 +build --BUILD_DATE=${BUILD_DATE}
