VERSION 0.6

FROM alpine

ARG DATE_TAG=$(date "+%Y%m%d")

build:
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE

    RUN set -ex \
        && apk update \
        && apk add bash openssh-client open-vm-tools

    COPY shutdown.sh /sbin/shutdown
    COPY entrypoint.sh /entrypoint.sh
    
    VOLUME /root/.ssh

    ENTRYPOINT ["/entrypoint.sh"]

    SAVE IMAGE --push mritd/open-vm-tools:${DATE_TAG} mritd/open-vm-tools

all:
    BUILD --platform=linux/amd64 +build
