VERSION 0.7

build:
    FROM debian:11-slim

    DO ../udcs+LABEL
    DO ../udcs/os/debian+UPGRADE

    ARG --required BUILD_DATE

    RUN set -ex \
        && apt update \
        && apt install openssh-client open-vm-tools -y \
        && rm -rf /var/lib/apt/lists/*

    COPY shutdown.sh /sbin/shutdown
    COPY entrypoint.sh /entrypoint.sh
    
    VOLUME /root/.ssh

    ENTRYPOINT ["/entrypoint.sh"]

    SAVE IMAGE --push ghcr.io/mritd/open-vm-tools:${BUILD_DATE} ghcr.io/mritd/open-vm-tools:latest

all:
    FROM mritd/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")

    BUILD --platform=linux/amd64 +build --BUILD_DATE=${BUILD_DATE}
