VERSION 0.7

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG

    RUN apk add privoxy --no-cache

    CMD ["privoxy","--no-daemon","/etc/privoxy/config"]

    SAVE IMAGE --push mritd/privoxy:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +build
