name: 'Init'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "${DOCKERHUB_USERNAME}" --password "${DOCKERHUB_PASSWORD}"
    - name: Install Deps
      run: |
        sudo apt update -y
        sudo apt install curl jq qemu binfmt-support qemu-user-static -y
    - name: Install Earthly
      run: |
        sudo curl -fsSL $(curl -fsSL https://api.github.com/repos/earthly/earthly/releases/latest | jq -r '.assets[].browser_download_url' | grep earthly-linux-amd64) > /usr/local/bin/earthly
        sudo chmod +x /usr/local/bin/earthly
