VERSION 0.7

build-idgen:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN --mount=type=cache,target=/go/pkg \
        go install -trimpath -ldflags "-w -s" github.com/mritd/idgen@latest

    SAVE ARTIFACT /go/bin/idgen

build:
    FROM ghcr.io/mritd/alpine
    
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    BUILD +build-idgen
    
    COPY +build-idgen/idgen /usr/bin/idgen
    
    ENTRYPOINT ["idgen"]

    CMD ["server"]

    SAVE IMAGE --push ghcr.io/mritd/idgen:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
