VERSION 0.7

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG

    RUN apk add aria2 --no-cache

    COPY aria2.conf /etc/aria2.conf
    COPY entrypoint.sh /entrypoint.sh

    ENV XDG_DATA_HOME /data

    VOLUME /data

    EXPOSE 6800/tcp
    EXPOSE 6789/tcp
    EXPOSE 6789/udp

    CMD ["/entrypoint.sh"]

    SAVE IMAGE --push mritd/aria2:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
