docker-cli:
    FROM docker
    SAVE ARTIFACT /usr/local/bin/docker /usr/local/bin/docker

docker-compose:
    FROM mritd/alpine
    RUN set -e \
        && export DOCKER_COMPOSE_URL="https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" \
        && curl -sSL ${DOCKER_COMPOSE_URL} > /tmp/docker-compose \
        && chmod +x /tmp/docker-compose
    SAVE ARTIFACT /tmp/docker-compose /tmp/docker-compose

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG

    COPY +docker-cli/usr/local/bin/docker /usr/local/bin/docker
    COPY +docker-compose/tmp/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose

    CMD ["/bin/bash"]

    SAVE IMAGE --push mritd/docker-cli:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
