VERSION 0.7

build-clash:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE

    ARG VERSION
    ARG BUILD_DATE

    RUN --mount=type=cache,target=/go/pkg set -e \
        && echo ">>>>>>>>>>>>>>> Build Version: ${VERSION} <<<<<<<<<<<<<<<" \
        && git clone --depth 1 --branch ${VERSION} https://github.com/MetaCubeX/Clash.Meta.git /go/src/clash-meta \
        && cd /go/src/clash-meta \
        && go build -o /clash -trimpath \
            -ldflags '-X "github.com/Dreamacro/clash/constant.Version=${VERSION}" \
                -X "github.com/Dreamacro/clash/constant.BuildTime=${DATE_TAG}" \
                -w -s -buildid='


    SAVE ARTIFACT /clash

build:
    FROM ghcr.io/mritd/alpine
    
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    ARG VERSION
    ARG BUILD_DATE

    ENV XDG_CONFIG_HOME /config
    ENV XDG_DATA_HOME /data

    BUILD +build-clash --VERSION=${VERSION}
    
    COPY +build-clash/clash /usr/bin/clash
    
    RUN set -e \
        && apk add ca-certificates tzdata iptables --no-cache
    
    VOLUME /config
    VOLUME /data
    VOLUME /root/.config/clash
    
    CMD ["clash"]

    SAVE IMAGE --push ghcr.io/mritd/clash-meta:latest ghcr.io/mritd/clash-meta:${VERSION} ghcr.io/mritd/clash-meta:${VERSION}-${BUILD_DATE}

all:
    DO ../udcs+BUILD_DATE

    ARG VERSION=$(curl -fsSL "https://api.github.com/repos/MetaCubeX/Clash.Meta/releases/latest" | jq -r '.tag_name')

    BUILD --platform=linux/amd64 --platform=linux/arm64 +build --VERSION=${VERSION} --BUILD_DATE=${BUILD_DATE}
