VERSION 0.7

build-clash:
    FROM golang:1.19-alpine
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE

    RUN --mount=type=cache,target=/go/pkg set -e \
        && echo ">>>>>>>>>>>>>>> Build Version: ${VERSION} <<<<<<<<<<<<<<<" \
        && git clone --depth 1 --branch ${VERSION} https://github.com/MetaCubeX/Clash.Meta.git /go/src/clash-meta \
        && cd /go/src/clash-meta \
        && go build -o /clash -trimpath \
            -ldflags '-X "github.com/Dreamacro/clash/constant.Version=${VERSION}" \
                -X "github.com/Dreamacro/clash/constant.BuildTime=${DATE_TAG}" \
                -w -s -buildid='


    SAVE ARTIFACT /clash

build:
    FROM mritd/alpine
    
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    BUILD +build-clash --build-arg --VERSION=${VERSION}
    
    ENV XDG_CONFIG_HOME /config
    ENV XDG_DATA_HOME /data
    
    COPY +build-clash/clash /usr/bin/clash
    
    RUN set -e \
        && apk add ca-certificates tzdata iptables --no-cache
    
    VOLUME /config
    VOLUME /data
    VOLUME /root/.config/clash
    
    CMD ["clash"]

    SAVE IMAGE --push mritd/clash-meta:latest mritd/clash-meta:${VERSION} mritd/clash-meta:${VERSION}-${DATE_TAG}

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --build-arg --BUILD_DATE=$(date "+%Y%m%d%H%M%S") --VERSION=$(curl -fsSL "https://api.github.com/repos/MetaCubeX/Clash.Meta/releases/latest" | jq -r '.tag_name') +build
