TIMEZONE:
    COMMAND
    ENV TZ Asia/Shanghai

    RUN apk add tzdata \
        && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo ${TZ} > /etc/timezone

UPGRADE:
    COMMAND
    RUN apk upgrade

COMMON_PKG:
    COMMAND
    RUN apk add bash tzdata bind-tools busybox-extras ca-certificates libc6-compat wget curl

INSTALL_BUILD_BASE:
    COMMAND
    RUN apk add --virtual build-dependencies alpine-sdk jq

REMOVE_BUILD_BASE:
    COMMAND
    RUN apk del build-dependencies

CLEAN_UP:
    COMMAND
    RUN rm -rf /var/cache/apk/*

