VERSION 0.7

build-tpclash:
    DO ../.udcs/image+GO_DEBIAN
    DO ../.udcs/os/debian+UPGRADE
    DO ../.udcs/os/debian+INSTALL_BUILD_BASE
    
    ENV REPO https://github.com/mritd/tpclash.git

    RUN set -ex \
        && curl -fsSL https://deb.nodesource.com/setup_18.x | bash \
        && apt install -y nodejs jq wget unzip coreutils \
        && sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/bin \
        && npm i -g pnpm \
        && git clone ${REPO} /go/src/tpclash \
        && cd /go/src/tpclash \
        && task build-tpclash-premium

    SAVE ARTIFACT /go/src/tpclash/build

build:
    FROM debian

    LABEL org.opencontainers.image.source="https://github.com/mritd/notibot"
    LABEL org.opencontainers.image.description="Telegram Notification Bot"
    LABEL org.opencontainers.image.licenses="Apache-2.0"
    
    DO ../.udcs/os/debian+TIMEZONE

    BUILD +build-tpclash
    
    COPY +build-tpclash/build /build

    EXPOSE 8080

    CMD ["notibot"]

    SAVE IMAGE --push mritd/tpclash:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
