VERSION 0.6

build-bandwagonmon:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    ENV GIT_REPO https://github.com/mritd/bandwagonmon.git
    ENV SRC_DIR /go/src/github.com/mritd/bandwagonmon

    RUN set -e \
        && git clone ${GIT_REPO} ${SRC_DIR} \
        && cd ${SRC_DIR} \
        && export GIT_COMMIT=$(git rev-list -1 HEAD) \
        && go install -trimpath -ldflags "-w -s -X main.commit=${GIT_COMMIT}"

    SAVE ARTIFACT /go/bin/bandwagonmon

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    BUILD +build-bandwagonmon
    
    COPY +build-bandwagonmon/bandwagonmon /usr/bin/bandwagonmon

    ENTRYPOINT ["bandwagonmon"]

    SAVE IMAGE --push mritd/bandwagonmon:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
