VERSION 0.7

ALPINE:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/alpine

DEBIAN:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/debian

UBUNTU:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/ubuntu

GOLANG:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/golang:1-alpine

GO:
    COMMAND
    DO +GOLANG

JDK8:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/eclipse-temurin:8-jdk

JDK8_OPENJ9:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/ibm-semeru-runtimes:open-8-jdk

JDK11:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/eclipse-temurin:11-jdk

JDK11_OPENJ9:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/ibm-semeru-runtimes:open-11-jdk

JDK17:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/eclipse-temurin:17-jdk

JDK17_OPENJ9:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/ibm-semeru-runtimes:open-17-jdk

NODE:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/node:lts-buster

NGINX:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/nginx:alpine

CONFLUENCE:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/atlassian/confluence-server:7-ubuntu

JIRA:
    COMMAND
    FROM ghcr.io/mritd/dockerhub/atlassian/jira-software:8.13
