VERSION 0.6

GOPROXY:
    COMMAND
    ENV GOPROXY https://goproxy.cn

FIX_DNS:
    COMMAND
    # set up nsswitch.conf for Go's "netgo" implementation
    # - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
    # - docker run --rm debian grep '^hosts:' /etc/nsswitch.conf
    RUN echo 'hosts: files dns' > /etc/nsswitch.conf
