VERSION 0.8

ALPINE:
    FUNCTION
    FROM alpine

DEBIAN:
    FUNCTION
    FROM debian

DEBIAN_SLIM:
    FUNCTION
    FROM debian:stable-slim

UBUNTU:
    FUNCTION
    FROM ubuntu

GOLANG:
    FUNCTION
    FROM golang:1-alpine

GOLANG_DEBIAN:
    FUNCTION
    FROM golang:1

GO:
    FUNCTION
    DO +GOLANG

GO_DEBIAN:
    FUNCTION
    DO +GOLANG_DEBIAN

RUST:
    FUNCTION
    FROM rust:alpine

RUST_DEFIAN:
    FUNCTION
    FROM rust

JDK8:
    FUNCTION
    FROM eclipse-temurin:8-jdk

JDK8_OPENJ9:
    FUNCTION
    FROM ibm-semeru-runtimes:open-8-jdk

JDK11:
    FUNCTION
    FROM eclipse-temurin:11-jdk

JDK11_OPENJ9:
    FUNCTION
    FROM ibm-semeru-runtimes:open-11-jdk

JDK17:
    FUNCTION
    FROM eclipse-temurin:17-jdk

JDK17_OPENJ9:
    FUNCTION
    FROM ibm-semeru-runtimes:open-17-jdk

NODE:
    FUNCTION
    FROM node:lts-buster

NGINX:
    FUNCTION
    FROM nginx:alpine

CONFLUENCE:
    FUNCTION
    FROM atlassian/confluence-server:7-ubuntu

JIRA:
    FUNCTION
    FROM atlassian/jira-software:8.13
