VERSION 0.8

build-derper:
    DO ../.udcs/image+GO
    DO ../.udcs/os/alpine+UPGRADE
    DO ../.udcs/os/alpine+INSTALL_BUILD_BASE
    
    ARG --required VERSION

    RUN --mount=type=cache,target=/go/pkg \
        go install -trimpath -ldflags "-w -s" tailscale.com/cmd/derper@${VERSION}

    SAVE ARTIFACT /go/bin/derper

build:
    FROM mritd/alpine

    DO ../.udcs/os/alpine+TIMEZONE
    DO ../.udcs/language/go+FIX_DNS

    ARG --required BUILD_DATE
    ARG --required VERSION

    ENV DERP_ADDR
    ENV DERP_HTTP_PORT
    ENV DERP_CONFIG
    ENV DERP_DOMAIN
    ENV DERP_CERT_MODE
    ENV DERP_CERT_DIR
    ENV DERP_STUN
    ENV DERP_STUN_PORT
    ENV DERP_VERIFY_CLIENTS

    BUILD +build-derper --VERSION=${VERSION}

    COPY +build-derper/derper /usr/bin/derper
    COPY entrypoint.sh /entrypoint.sh

    EXPOSE 80/tcp
    EXPOSE 443/tcp
    EXPOSE 3478/udp

    VOLUME ["/var/run/tailscale", "/var/lib/derper"]

    ENTRYPOINT ["/entrypoint.sh"]

    SAVE IMAGE --push mritd/derper:latest mritd/derper:${VERSION} mritd/derper:${VERSION}-${BUILD_DATE}

all:
    FROM mritd/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")
    ARG VERSION=$(curl -sSL "https://api.github.com/repos/tailscale/tailscale/releases/latest" | jq -r '.tag_name')

    BUILD --platform=linux/amd64 --platform=linux/arm64 +build --BUILD_DATE=${BUILD_DATE} --VERSION=${VERSION}
