VERSION 0.7

build-derper:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN --mount=type=cache,target=/go/pkg \
        go install -trimpath -ldflags "-w -s" tailscale.com/cmd/derper@main

    SAVE ARTIFACT /go/bin/derper

build:
    FROM mritd/alpine

    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    ENV DERP_ADDR :8080
    ENV DERP_HTTP_PORT 8080
    ENV DERP_DOMAIN your.domain.com
    ENV DERP_CERT_MODE letsencrypt
    ENV DERP_CERT_DIR /var/run/tailscale
    ENV DERP_STUN true
    ENV DERP_STUN_PORT 3456
    ENV DERP_VERIFY_CLIENTS true

    BUILD +build-derper

    COPY +build-derper/derper /usr/bin/derper

    EXPOSE 8080/tcp
    EXPOSE 3456/udp

    VOLUME ["/var/run/tailscale", "/var/lib/derper"]

    CMD derper \
            --a=${DERP_ADDR} \
            --hostname=${DERP_DOMAIN} \
            --certmode=${DERP_CERT_MODE} \
            --certdir=${DERP_CERT_DIR} \
            --stun=${DERP_STUN} \
            --stun-port=${DERP_STUN_PORT} \
            --http-port=${DERP_HTTP_PORT} \
            --verify-clients=${DERP_VERIFY_CLIENTS}

    SAVE IMAGE --push mritd/derper:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +build
