VERSION 0.7

docker-cli:
    FROM docker

    SAVE ARTIFACT /usr/local/bin/docker /tmp/docker

docker-compose:
    FROM ghcr.io/mritd/alpine

    RUN set -ex \
        && download_url="https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" \
        && curl -sSL ${download_url} > /tmp/docker-compose \
        && chmod +x /tmp/docker-compose

    SAVE ARTIFACT /tmp/docker-compose /tmp/docker-compose

kubectl:
    FROM ghcr.io/mritd/alpine

    ARG --required OS_ARCH

    RUN set -ex \
        && version=$(curl -sSL https://dl.k8s.io/release/stable.txt) \
        && curl -sSL "https://dl.k8s.io/release/${version}/bin/linux/${OS_ARCH}/kubectl" > /tmp/kubectl \
        && chmod +x /tmp/kubectl

    SAVE ARTIFACT /tmp/kubectl /tmp/kubectl

nerdctl:
    FROM ghcr.io/mritd/alpine

    ARG --required OS_ARCH

    RUN set -ex \
        && download_url=$(curl -sSL https://api.github.com/repos/containerd/nerdctl/releases | \
            jq -r '.[0].assets[].browser_download_url' | grep -v full | grep "linux-${OS_ARCH}") \
        && curl -sSL ${download_url} > nerdctl-${OS_ARCH}.tar.gz \
        && tar -zxvf nerdctl-${OS_ARCH}.tar.gz -C /tmp

    SAVE ARTIFACT /tmp/nerdctl /tmp/nerdctl

podman:
    FROM ghcr.io/mritd/alpine

    ARG --required OS_ARCH

    RUN set -ex \
        && download_url="https://github.com/containers/podman/releases/latest/download/podman-remote-static-linux_${OS_ARCH}.tar.gz" \
        && curl -sSL ${download_url} > podman-remote-static-linux_${OS_ARCH}.tar.gz \
        && tar -zxvf podman-remote-static-linux_${OS_ARCH}.tar.gz -C /tmp \
        && mv /tmp/bin/podman-remote-static-linux_${OS_ARCH} /tmp/podman

    SAVE ARTIFACT /tmp/podman /tmp/podman

build:
    FROM ghcr.io/mritd/alpine

    ARG --required OS_ARCH
    ARG --required BUILD_DATE
    
    BUILD +docker-cli --OS_ARCH=${OS_ARCH}
    BUILD +docker-compose --OS_ARCH=${OS_ARCH}
    BUILD +kubectl --OS_ARCH=${OS_ARCH}
    BUILD +nerdctl --OS_ARCH=${OS_ARCH}
    BUILD +podman --OS_ARCH=${OS_ARCH}

    COPY +docker-cli/tmp/docker /usr/local/bin/docker
    COPY +docker-compose/tmp/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose
    COPY +kubectl/tmp/kubectl /usr/local/bin/kubectl
    COPY +nerdctl/tmp/nerdctl /usr/local/bin/nerdctl
    COPY +podman/tmp/podman /usr/local/bin/podman

    CMD ["bash"]

    SAVE IMAGE --push ghcr.io/mritd/container-cli:${BUILD_DATE} ghcr.io/mritd/container-cli:latest

all:
    #DO ../udcs+BUILD_DATE
    #DO ../udcs+OS_ARCH
    FROM ghcr.io/mritd/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S") 

    FROM mritd/osarch

    ARG OS_ARCH=$(osarch)

    BUILD --platform=linux/amd64 +build --BUILD_DATE=${BUILD_DATE} --OS_ARCH=${OS_ARCH}
