build-certmonitor:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN --mount=type=cache,target=/go/pkg \
        export BUILD_DATE=$(date "+%F %T") \
        && export COMMIT_SHA1=$(curl -s "https://api.github.com/repos/mritd/certmonitor/commits/master" | jq .sha) \ 
        && go install -ldflags \
            "-X 'github.com/mritd/certmonitor/cmd.version=master' \
             -X 'github.com/mritd/certmonitor/cmd.buildTime=${BUILD_DATE}' \
             -X 'github.com/mritd/certmonitor/cmd.commit=${COMMIT_SHA1}'\
             -w -s" \
            github.com/mritd/certmonitor@master

    SAVE ARTIFACT /go/bin/certmonitor /certmonitor

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    BUILD +build-certmonitor
    
    COPY +build-certmonitor/certmonitor /usr/bin/certmonitor
    
    CMD ["certmonitor", "--config", "/etc/certmonitor.yaml"]

    SAVE IMAGE --push mritd/certmonitor:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +build
