VERSION 0.6

build-derper:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN --mount=type=cache,target=/go/pkg \
        go install tailscale.com/cmd/derper@main

    SAVE ARTIFACT /go/bin/derper

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    ENV DERP_ADDR :8080
    ENV DERP_HTTP_PORT 8080
    ENV DERP_DOMAIN your.domain.com
    ENV DERP_CERT_MODE letsencrypt
    ENV DERP_CERT_DIR /var/run/tailscale
    ENV DERP_STUN true
    ENV DERP_VERIFY_CLIENTS false
    
    BUILD +build-derper
    
    COPY +build-derper/derper /usr/bin/derper

    VOLUME ["/var/run/tailscale"]

    CMD deper \
            --hostname=${DERP_DOMAIN} \
            --certmode=${DERP_CERT_MODE} \
            --certdir=$DERP_CERT_DIR} \
            --a=${DERP_ADDR} \
            --stun=${DERP_STUN}  \
            --http-port=${DERP_HTTP_PORT} \
            --verify-clients=${DERP_VERIFY_CLIENTS}

    SAVE IMAGE --push mritd/derper:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +build
