LABEL:
    COMMAND
    LABEL maintainer="mritd <mritd@linux.com>"

MULTIARCH:
    COMMAND
    LOCALLY
    RUN apt install qemu binfmt-support qemu-user-static -y \
        && docker run --rm --privileged multiarch/qemu-user-static --reset -p yes \
        && docker stop earthly-buildkitd || true
