VERSION 0.8

TIMEZONE:
    FUNCTION
    ENV TZ Asia/Shanghai

    RUN export DEBIAN_FRONTEND=noninteractive \
        && apt install -qq tzdata -y \
        && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo ${TZ} > /etc/timezone \
        && dpkg-reconfigure --frontend noninteractive tzdata \
        && rm -rf /var/lib/apt/lists/*

UPGRADE:
    FUNCTION
    RUN apt update -qq \
        && apt upgrade -qq -y \
        && apt autoremove -y \
        && apt autoclean -y \
        && rm -rf /var/lib/apt/lists/*

COMMON_PKG:
    FUNCTION
    RUN apt update -qq \
        && apt install -qq tzdata ca-certificates wget curl nload iftop htop unzip procps dnsutils net-tools iputils-ping git jq -y \
        && rm -rf /var/lib/apt/lists/*

LOCALE:
    FUNCTION
    ENV LANG en_US.UTF-8
    ENV LC_ALL en_US.UTF-8
    ENV LANGUAGE en_US:en

    RUN apt update -qq \
        && apt install -qq locales fonts-noto-cjk -y \
        && locale-gen --purge en_US.UTF-8 zh_CN.UTF-8 \
        && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
        && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
        && echo 'LANGUAGE="en_US:en"' >> /etc/default/locale \
        && rm -rf /var/lib/apt/lists/*

INSTALL_BUILD_BASE:
    FUNCTION
    RUN apt update -qq \
        && apt install -qq build-essential -y \
        && rm -rf /var/lib/apt/lists/*
        
