VERSION 0.7

LABEL:
    COMMAND
    LABEL maintainer="mritd <mritd@linux.com>"
    LABEL repository="https://github.com/mritd/autobuild"
    LABEL description="GitHub Action + Earthly Auto Build"

BUILD_DATE:
    COMMAND
    FROM mritd/alpine
    ARG --global BUILD_DATE=$(date "+%Y%m%d%H%M%S")

TINI:
    COMMAND
    ENV TINI_VERSION v0.19.0
    ENV TINI_DOWNLOAD_URL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-amd64

    RUN curl -sSL ${TINI_DOWNLOAD_URL} > /usr/bin/tini \
        && chmod +x /usr/bin/tini

PREZTO:
    COMMAND
    ENV PREZTO_INIT_SCRIPT https://raw.githubusercontent.com/mritd/init/master/prezto/init.sh
    RUN curl -sSL ${PREZTO_INIT_SCRIPT} | bash

VIM:
    COMMAND
    ENV VIM_INIT_SCRIPT https://raw.githubusercontent.com/mritd/init/master/vim/init.sh
    RUN curl -sSL ${VIM_INIT_SCRIPT} | bash

GO_TASK:
    COMMAND
    RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
