VERSION 0.6

TIMEZONE:
    COMMAND
    ENV TZ Asia/Shanghai

    RUN export DEBIAN_FRONTEND=noninteractive \
        && apt install tzdata -y \
        && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo ${TZ} > /etc/timezone \
        && dpkg-reconfigure --frontend noninteractive tzdata \
        && rm -rf /var/lib/apt/lists/*

UPGRADE:
    COMMAND
    RUN apt update \
        && apt upgrade -y \
        && apt autoremove -y \
        && apt autoclean -y \
        && rm -rf /var/lib/apt/lists/*

COMMON_PKG:
    COMMAND
    RUN apt update \
        && apt install tzdata ca-certificates wget curl nload iftop htop unzip procps dnsutils iputils-ping git -y \
        && rm -rf /var/lib/apt/lists/*

LOCALE:
    COMMAND
    ENV LANG en_US.UTF-8
    ENV LC_ALL en_US.UTF-8
    ENV LANGUAGE en_US:en

    RUN apt update \
        && apt install locales -y \
        && locale-gen --purge en_US.UTF-8 zh_CN.UTF-8 \
        && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
        && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
        && echo 'LANGUAGE="en_US:en"' >> /etc/default/locale \
        && rm -rf /var/lib/apt/lists/*

INSTALL_BUILD_BASE:
    COMMAND
    RUN apt update \
        && apt install build-essential -y \
        && rm -rf /var/lib/apt/lists/*
        
