VERSION 0.6

FROM mritd/alpine

ARG DATE_TAG=$(date "+%Y%m%d")

build-dnsacme:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    DO ../udcs+GO_TASK
    
    ENV REPO https://github.com/mritd/dnsacme.git
    ENV SRC_PATH /go/src/github.com/mritd/dnsacme

    RUN set -e \
        && git clone ${REPO} ${SRC_PATH} \
        && cd ${SRC_PATH} && task

    SAVE ARTIFACT ${SRC_PATH}/build/dnsacme-local

build:
    DO ../udcs/image+ALPINE
    DO ../udcs+LABEL
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+COMMON_PKG
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    RUN apk add openssh-client --no-cache

    ENV XDG_CONFIG_HOME /data

    BUILD +build-dnsacme
    
    COPY +build-dnsacme/dnsacme-local /usr/local/bin/dnsacme

    VOLUME /data

    CMD ["dnsacme"]
    
    SAVE IMAGE --push mritd/dnsacme:latest mritd/dnsacme:${DATE_TAG}

unraid:
    BUILD +build

    ENV ACME_OBTAINED_HOOK unraid

    COPY unraid.sh /usr/local/bin/unraid
    COPY entrypoint.sh /entrypoint.sh

    VOLUME /host_ssh
    VOLUME /host_certs

    ENTRYPOINT ["/entrypoint.sh"]

    SAVE IMAGE --push mritd/dnsacme:unraid mritd/dnsacme:unraid-${DATE_TAG}

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
    BUILD --platform=linux/amd64 --platform=linux/arm64 +unraid
