VERSION 0.7

alpine:
    FROM alpine:latest
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/alpine:latest

debian:
    FROM debian:latest
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/debian:latest

ubuntu:
    FROM ubuntu:latest
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/ubuntu:latest

golang:
    FROM golang:1-alpine
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/golang:1-alpine

eclipse-temurin:
    FROM eclipse-temurin:8-jdk
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/eclipse-temurin:8-jdk

    FROM eclipse-temurin:11-jdk
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/eclipse-temurin:11-jdk

    FROM eclipse-temurin:17-jdk
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/eclipse-temurin:17-jdk

ibm-semeru-runtimes:
    FROM ibm-semeru-runtimes:open-8-jdk
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/ibm-semeru-runtimes:open-8-jdk

    FROM ibm-semeru-runtimes:open-11-jdk
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/ibm-semeru-runtimes:open-11-jdk

    FROM ibm-semeru-runtimes:open-17-jdk
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/ibm-semeru-runtimes:open-17-jdk

node:
    FROM node:lts-buster
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/node:lts-buster

nginx:
    FROM nginx:alpine
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/nginx:alpine

confluence-server:
    FROM atlassian/confluence-server:7-ubuntu
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/atlassian/confluence-server:7-ubuntu

jira-software:
    FROM atlassian/jira-software:8.13
    DO ../udcs+LABEL
    SAVE IMAGE --push ghcr.io/dockerhub/atlassian/atlassian/jira-software:8.13


all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +alpine
    BUILD --platform=linux/amd64 --platform=linux/arm64 +debian
    BUILD --platform=linux/amd64 --platform=linux/arm64 +ubuntu
    BUILD --platform=linux/amd64 --platform=linux/arm64 +golang
    BUILD --platform=linux/amd64 +eclipse-temurin
    BUILD --platform=linux/amd64 +ibm-semeru-runtimes
    BUILD --platform=linux/amd64 +node
    BUILD --platform=linux/amd64 +nginx
    BUILD --platform=linux/amd64 +confluence-server
    BUILD --platform=linux/amd64 +jira-software
