VERSION 0.7

alpine:
    FROM alpine:latest
    DO ../.udcs+LABEL
    SAVE IMAGE --push alpine:latest

debian:
    FROM debian:latest
    DO ../.udcs+LABEL
    SAVE IMAGE --push debian:latest

ubuntu:
    FROM ubuntu:latest
    DO ../.udcs+LABEL
    SAVE IMAGE --push ubuntu:latest

golang:
    FROM golang:1-alpine
    DO ../.udcs+LABEL
    SAVE IMAGE --push golang:1-alpine

    FROM golang:1
    DO ../.udcs+LABEL
    SAVE IMAGE --push golang:1

eclipse-temurin:
    FROM eclipse-temurin:8-jdk
    DO ../.udcs+LABEL
    SAVE IMAGE --push eclipse-temurin:8-jdk

    FROM eclipse-temurin:11-jdk
    DO ../.udcs+LABEL
    SAVE IMAGE --push eclipse-temurin:11-jdk

    FROM eclipse-temurin:17-jdk
    DO ../.udcs+LABEL
    SAVE IMAGE --push eclipse-temurin:17-jdk

ibm-semeru-runtimes:
    FROM ibm-semeru-runtimes:open-8-jdk
    DO ../.udcs+LABEL
    SAVE IMAGE --push ibm-semeru-runtimes:open-8-jdk

    FROM ibm-semeru-runtimes:open-11-jdk
    DO ../.udcs+LABEL
    SAVE IMAGE --push ibm-semeru-runtimes:open-11-jdk

    FROM ibm-semeru-runtimes:open-17-jdk
    DO ../.udcs+LABEL
    SAVE IMAGE --push ibm-semeru-runtimes:open-17-jdk

node:
    FROM node:lts-buster
    DO ../.udcs+LABEL
    SAVE IMAGE --push node:lts-buster

nginx:
    FROM nginx:alpine
    DO ../.udcs+LABEL
    SAVE IMAGE --push nginx:alpine

confluence-server:
    FROM atlassian/confluence-server:7-ubuntu
    DO ../.udcs+LABEL
    SAVE IMAGE --push atlassian/confluence-server:7-ubuntu

jira-software:
    FROM atlassian/jira-software:8.13
    DO ../.udcs+LABEL
    SAVE IMAGE --push atlassian/jira-software:8.13


all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +alpine
    BUILD --platform=linux/amd64 --platform=linux/arm64 +debian
    BUILD --platform=linux/amd64 --platform=linux/arm64 +ubuntu
    BUILD --platform=linux/amd64 --platform=linux/arm64 +golang
    BUILD --platform=linux/amd64 --platform=linux/arm64 +nginx
    BUILD --platform=linux/amd64 +eclipse-temurin
    BUILD --platform=linux/amd64 +ibm-semeru-runtimes
    BUILD --platform=linux/amd64 +node
    BUILD --platform=linux/amd64 +confluence-server
    BUILD --platform=linux/amd64 +jira-software
