VERSION 0.7

build-ddns:
    DO ../.udcs/image+GO
    DO ../.udcs/os/alpine+UPGRADE
    DO ../.udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN --mount=type=cache,target=/go/pkg \
        go install -trimpath -ldflags "-w -s" github.com/mritd/ddns@latest

    SAVE ARTIFACT /go/bin/ddns

build:
    FROM mritd/alpine
    
    DO ../.udcs/os/alpine+TIMEZONE
    DO ../.udcs/language/go+FIX_DNS

    BUILD +build-ddns
    
    COPY +build-ddns/ddns /usr/bin/ddns
    
    ENTRYPOINT ["ddns"]

    SAVE IMAGE --push mritd/ddns:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
