VERSION 0.8

TIMEZONE:
    FUNCTION
    ENV TZ Asia/Shanghai

    RUN apk add tzdata --no-cache \
        && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo ${TZ} > /etc/timezone

UPGRADE:
    FUNCTION
    RUN apk upgrade --no-cache

COMMON_PKG:
    FUNCTION
    RUN apk add bash tzdata bind-tools busybox-extras ca-certificates libc6-compat vim wget curl jq git --no-cache

INSTALL_BUILD_BASE:
    FUNCTION
    RUN apk add --virtual build-dependencies alpine-sdk --no-cache

REMOVE_BUILD_BASE:
    FUNCTION
    RUN apk del build-dependencies --no-cache 

