VERSION 0.7

build:
    DO ../udcs/image+JDK11
    DO ../udcs+LABEL

    ENV GATEWAY_DOWNLOAD_URL https://download2.interactivebrokers.com/portal/clientportal.gw.zip

    RUN set -ex \
        && apt update \
        && apt install wget unzip -y \
        && mkdir -p /opt/clientportal \
        && cd /opt/clientportal \
        && wget -q ${GATEWAY_DOWNLOAD_URL} -O clientportal.gw.zip \
        && unzip clientportal.gw.zip \
        && rm -f clientportal.gw.zip \
        && apt autoclean -y \
        && rm -rf /var/lib/apt/lists/*

    COPY conf.yaml /opt/clientportal/root/conf.yaml

    WORKDIR /opt/clientportal

    CMD ["bin/run.sh","root/conf.yaml"]

    SAVE IMAGE --push mritd/clientportal:latest

all:
    BUILD --platform=linux/amd64 +build
