VERSION 0.7

build-notibot:
    DO ../.udcs/image+GO
    DO ../.udcs/os/alpine+UPGRADE
    DO ../.udcs/os/alpine+INSTALL_BUILD_BASE
    
    ARG VERSION
    ARG BUILD_DATE

    RUN --mount=type=cache,target=/go/pkg set -e \
        && echo ">>>>>>>>>>>>>>> Build Version: ${VERSION} <<<<<<<<<<<<<<<" \
        && git clone --depth 1 --branch ${VERSION} https://github.com/mritd/notibot.git /go/src/notibot \
        && cd /go/src/notibot \
        && export commit_hash=$(git rev-parse HEAD) \
        && go install -trimpath -ldflags "-w -s \
            -X \"main.version=${VERSION}\" \
            -X \"main.build=${BUILD_DATE}\" \
            -X \"main.commit=${commit_hash}\""

    SAVE ARTIFACT /go/bin/notibot

build:
    FROM mritd/alpine

    LABEL org.opencontainers.image.source="https://github.com/mritd/notibot"
    LABEL org.opencontainers.image.description="Telegram Notification Bot"
    LABEL org.opencontainers.image.licenses="Apache-2.0"

    ARG VERSION
    ARG BUILD_DATE

    DO ../.udcs/os/alpine+TIMEZONE
    DO ../.udcs/language/go+FIX_DNS

    BUILD +build-notibot --VERSION=${VERSION} --BUILD_DATE=${BUILD_DATE}
    
    COPY +build-notibot/notibot /usr/bin/notibot

    EXPOSE 8080

    CMD ["notibot"]

    SAVE IMAGE --push mritd/notibot:latest mritd/notibot:${VERSION} mritd/notibot:${VERSION}-${BUILD_DATE}

all:
    FROM mritd/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")
    ARG VERSION=$(curl -fsSL "https://api.github.com/repos/mritd/notibot/releases/latest" | jq -r '.tag_name')

    BUILD --platform=linux/amd64 --platform=linux/arm64 +build --VERSION=${VERSION} --BUILD_DATE=${BUILD_DATE}
