VERSION 0.7

build-notibot:
    DO ../udcs/image+GO
    DO ../udcs/os/alpine+UPGRADE
    DO ../udcs/os/alpine+INSTALL_BUILD_BASE
    
    RUN set -ex \
        && go install -trimpath -ldflags "-w -s" github.com/mritd/notibot@main

    SAVE ARTIFACT /go/bin/notibot

build:
    FROM mritd/alpine

    LABEL org.opencontainers.image.source="https://github.com/mritd/notibot"
    LABEL org.opencontainers.image.description="Telegram Notification Bot"
    LABEL org.opencontainers.image.licenses="Apache-2.0"
    
    DO ../udcs/os/alpine+TIMEZONE
    DO ../udcs/language/go+FIX_DNS

    BUILD +build-notibot
    
    COPY +build-notibot/notibot /usr/bin/notibot

    EXPOSE 8080

    CMD ["notibot"]

    SAVE IMAGE --push ghcr.io/mritd/notibot:latest

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
