name: mritd/aria2

on:
  schedule:
    - cron: 0 1 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  aria2:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: aria2
