name: mritd/bandwagonmon

on:
  schedule:
    - cron: 0 2 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  bandwagonmon:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: bandwagonmon
