name: mritd/caddy

on:
  schedule:
    - cron: 0 3 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  caddy:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: caddy
