name: mritd/ci-runner

on:
  schedule:
    - cron: 0 4 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  ci-runner:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: ci-runner
