name: mritd/ddns

on:
  schedule:
    - cron: 0 7 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  ddns:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: ddns
