name: mritd/makeself

on:
  schedule:
    - cron: 0 12 * * 1
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  makeself:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: makeself
