name: mritd/makeself

on:
  schedule:
    - cron: 0 13 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  makeself:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: makeself
