name: mritd/nginx-singlepage

on:
  schedule:
    - cron: 0 14 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  nginx-singlepage:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: nginx-singlepage
