name: mritd/open-vm-tools

on:
  schedule:
    - cron: 0 16 * * 1
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  open-vm-tools:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: open-vm-tools
