name: mritd/ssh

on:
  schedule:
    - cron: 0 22 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  ssh:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: ssh
