name: mritd/tgid

on:
  schedule:
    - cron: 0 23 * * 1
  workflow_call:
  workflow_dispatch:

jobs:
  tgid:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: tgid
