name: mritd/tuic-server

on:
  schedule:
    - cron: 0 1 * * 2
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  tuic-server:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: tuic-server
