name: mritd/tuic-server

on:
  schedule:
    - cron: 0 0 * * 2
  workflow_call:
  workflow_dispatch:

jobs:
  tuic-server:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: tuic-server
